---
engines:
  eslint:
    enabled: true
  ember-template-lint:
    enabled: true
    channel: beta
  fixme:
    enabled: true
ratings:
  paths:
  - "addon/**"
exclude_paths:
- "*.md"
- "blueprints/**/*"
- "config/**/*"
- "dist/**/*"
- "vendor/**/*"
- "node_modules/**/*"
- "bower_components/**/*"
- "tmp/**/*"
