import EmberRouter from '@ember/routing/router';
import config from './config/environment';
import RouterScroll from 'ember-router-scroll';

const Router = EmberRouter.extend(RouterScroll, {
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function () {
  this.route('docs', function() { // docs homepage (required)
    this.route('recipes');
    this.route('integration');
    this.route('testing');
    this.route('aws');
    this.route('helper', function() {
      this.route('file-queue');
    });
    this.route('api', function() { // autogenerated API homepage (required)
      this.route('item', { path: '/*path' }); // autogenerated API subpages (required)
    });
  });

  this.route('not-found', { path: '/*path' });
});

export default Router;
