name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: '16.x'

jobs:
  lint:
    name: Lint addon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Lint
        run: pnpm --filter ember-file-upload lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Test
        run: pnpm --filter test-app test:ember --launch chrome

  typecheck:
    name: 'Typecheck ${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    needs: lint
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@5.0
          - typescript@5.1
          - typescript@5.2
          - typescript@5.3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: 'Change TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-app

      - name: Lint
        run: |
          pnpm --filter "test-app*" exec tsc -v;
          pnpm --filter "test-app*" exec glint --version;
          pnpm --filter "test-app*" lint:types;

  floating-dependencies:
    name: Tests - Floating Dependencies
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          args: --no-lockfile

      - name: Test
        run: pnpm --filter test-app test:ember --launch chrome

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          [
            ember-3.25,
            ember-lts-3.28,
            ember-release,
            ember-beta,
            ember-canary,
            embroider-safe,
            embroider-optimized,
          ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: pnpm --filter test-app test:ember-try $EMBER_TRY_SCENARIO
