name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: '16.x'

jobs:
  lint:
    name: Lint addon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter ember-file-upload lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm --filter test-app test:ember --launch chrome

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter test-app lint:types

  floating-dependencies:
    name: Tests - Floating Dependencies
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: rm pnpm-lock.yaml && pnpm install

      - name: Test
        run: pnpm --filter test-app test:ember --launch chrome

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          [
            ember-3.25,
            ember-lts-3.28,
            ember-release,
            ember-beta,
            ember-canary,
            embroider-safe,
            embroider-optimized,
          ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: pnpm --filter test-app test:ember-try $EMBER_TRY_SCENARIO
